### ISSUE TITLE
postbox.c has depends on fltk

### ISSUE THREAD

**Issue by retuxx** [IRIXUser/XwinTox#21]
```c
#ifdef __cplusplus
#include <FL/FL.H>
#endif
```

Isn't libsunshine a standalone library? If yes, it shouldn't depend on fltk which is a gui library.

**Comment by IRIXUser** [comment]
Ah, yeah, that's from when postbox.c was part of XwinTox propler. I'm trying to avoid that kind of complicated threading, as well as ensuring genericity now, so that can go.
